// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNode(arg1) {
  return window['go']['main']['App']['AddNode'](arg1);
}

export function BackupNow(arg1) {
  return window['go']['main']['App']['BackupNow'](arg1);
}

export function CreateInstance(arg1) {
  return window['go']['main']['App']['CreateInstance'](arg1);
}

export function CurseForgeEnabled() {
  return window['go']['main']['App']['CurseForgeEnabled']();
}

export function CurseForgeKeyConfigured() {
  return window['go']['main']['App']['CurseForgeKeyConfigured']();
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function DockerAvailable() {
  return window['go']['main']['App']['DockerAvailable']();
}

export function GetAlertSettings(arg1) {
  return window['go']['main']['App']['GetAlertSettings'](arg1);
}

export function GetCommandCapability(arg1) {
  return window['go']['main']['App']['GetCommandCapability'](arg1);
}

export function GetSnapshot(arg1) {
  return window['go']['main']['App']['GetSnapshot'](arg1);
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListInstances() {
  return window['go']['main']['App']['ListInstances']();
}

export function ListNodes() {
  return window['go']['main']['App']['ListNodes']();
}

export function ListSchedules(arg1) {
  return window['go']['main']['App']['ListSchedules'](arg1);
}

export function ListTemplates() {
  return window['go']['main']['App']['ListTemplates']();
}

export function NodeStatus() {
  return window['go']['main']['App']['NodeStatus']();
}

export function ProbeNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProbeNode'](arg1, arg2, arg3);
}

export function QueryEvents(arg1) {
  return window['go']['main']['App']['QueryEvents'](arg1);
}

export function QueryMetrics(arg1, arg2) {
  return window['go']['main']['App']['QueryMetrics'](arg1, arg2);
}

export function QueryMetricsSummary(arg1) {
  return window['go']['main']['App']['QueryMetricsSummary'](arg1);
}

export function RemoveInstance(arg1, arg2) {
  return window['go']['main']['App']['RemoveInstance'](arg1, arg2);
}

export function RemoveNode(arg1) {
  return window['go']['main']['App']['RemoveNode'](arg1);
}

export function RestartInstance(arg1) {
  return window['go']['main']['App']['RestartInstance'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function RetryDocker() {
  return window['go']['main']['App']['RetryDocker']();
}

export function SendCommand(arg1, arg2) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2);
}

export function SetAlertSettings(arg1, arg2) {
  return window['go']['main']['App']['SetAlertSettings'](arg1, arg2);
}

export function SetCurseForgeAPIKey(arg1) {
  return window['go']['main']['App']['SetCurseForgeAPIKey'](arg1);
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}

export function SubscribeLogs(arg1) {
  return window['go']['main']['App']['SubscribeLogs'](arg1);
}

export function SubscribeStats(arg1) {
  return window['go']['main']['App']['SubscribeStats'](arg1);
}

export function UnsubscribeLogs(arg1) {
  return window['go']['main']['App']['UnsubscribeLogs'](arg1);
}

export function UnsubscribeStats(arg1) {
  return window['go']['main']['App']['UnsubscribeStats'](arg1);
}

export function UpsertSchedule(arg1) {
  return window['go']['main']['App']['UpsertSchedule'](arg1);
}
