// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {protocol} from '../models';
import {main} from '../models';

export function BackupNow(arg1:string):Promise<protocol.BackupMeta>;

export function CreateInstance(arg1:main.CreateInstanceRequest):Promise<string>;

export function DeleteSchedule(arg1:string):Promise<void>;

export function DockerAvailable():Promise<boolean>;

export function GetAlertSettings(arg1:string):Promise<main.AlertSettingsDTO>;

export function GetCommandCapability(arg1:string):Promise<main.CommandCapabilityDTO>;

export function GetSnapshot(arg1:string):Promise<main.SnapshotDTO>;

export function ListBackups(arg1:string):Promise<Array<protocol.BackupMeta>>;

export function ListInstances():Promise<Array<main.InstanceDTO>>;

export function ListSchedules(arg1:string):Promise<Array<main.ScheduleDTO>>;

export function ListTemplates():Promise<Array<main.TemplateDTO>>;

export function NodeStatus():Promise<Array<main.NodeStatusDTO>>;

export function QueryEvents(arg1:main.QueryEventsRequest):Promise<Array<main.EventDTO>>;

export function RemoveInstance(arg1:string,arg2:boolean):Promise<void>;

export function RestartInstance(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string,arg2:string):Promise<void>;

export function RetryDocker():Promise<void>;

export function SendCommand(arg1:string,arg2:protocol.GameCommand):Promise<protocol.CommandResult>;

export function SetAlertSettings(arg1:string,arg2:main.AlertSettingsRequest):Promise<void>;

export function StartInstance(arg1:string):Promise<void>;

export function StopInstance(arg1:string):Promise<void>;

export function SubscribeLogs(arg1:string):Promise<void>;

export function SubscribeStats(arg1:string):Promise<void>;

export function UnsubscribeLogs(arg1:string):Promise<void>;

export function UnsubscribeStats(arg1:string):Promise<void>;

export function UpsertSchedule(arg1:main.UpsertScheduleRequest):Promise<string>;
