// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {protocol} from '../models';

export function AddNode(arg1:main.AddNodeRequest):Promise<void>;

export function BackupNow(arg1:string):Promise<protocol.BackupMeta>;

export function CreateInstance(arg1:main.CreateInstanceRequest):Promise<string>;

export function CurseForgeEnabled():Promise<boolean>;

export function CurseForgeKeyConfigured():Promise<boolean>;

export function DeleteBackup(arg1:string,arg2:string):Promise<void>;

export function DeleteSchedule(arg1:string):Promise<void>;

export function DockerAvailable():Promise<boolean>;

export function GetAlertSettings(arg1:string):Promise<main.AlertSettingsDTO>;

export function GetCommandCapability(arg1:string):Promise<main.CommandCapabilityDTO>;

export function GetSnapshot(arg1:string):Promise<main.SnapshotDTO>;

export function InstanceDiskUsage(arg1:string):Promise<main.DiskUsageDTO>;

export function ListBackups(arg1:string):Promise<Array<protocol.BackupMeta>>;

export function ListContainers():Promise<Array<main.ContainerDTO>>;

export function ListImages():Promise<Array<main.ImageDTO>>;

export function ListInstances():Promise<Array<main.InstanceDTO>>;

export function ListNodes():Promise<Array<main.NodeInfoDTO>>;

export function ListSchedules(arg1:string):Promise<Array<main.ScheduleDTO>>;

export function ListTemplates():Promise<Array<main.TemplateDTO>>;

export function NodeStatus():Promise<Array<main.NodeStatusDTO>>;

export function ProbeNode(arg1:string,arg2:string,arg3:boolean):Promise<main.ProbeNodeResultDTO>;

export function PruneImages():Promise<main.PruneResultDTO>;

export function QueryEvents(arg1:main.QueryEventsRequest):Promise<Array<main.EventDTO>>;

export function QueryMetrics(arg1:string,arg2:number):Promise<Array<main.MetricPointDTO>>;

export function QueryMetricsSummary(arg1:number):Promise<Array<main.MetricPointDTO>>;

export function RemoveContainer(arg1:string,arg2:boolean):Promise<void>;

export function RemoveImage(arg1:string,arg2:boolean):Promise<void>;

export function RemoveInstance(arg1:string,arg2:boolean):Promise<void>;

export function RemoveNode(arg1:string):Promise<void>;

export function RestartInstance(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string,arg2:string):Promise<void>;

export function RetryDocker():Promise<void>;

export function SendCommand(arg1:string,arg2:protocol.GameCommand):Promise<protocol.CommandResult>;

export function SetAlertSettings(arg1:string,arg2:main.AlertSettingsRequest):Promise<void>;

export function SetCurseForgeAPIKey(arg1:string):Promise<void>;

export function StartInstance(arg1:string):Promise<void>;

export function StopInstance(arg1:string):Promise<void>;

export function SubscribeLogs(arg1:string):Promise<void>;

export function SubscribeStats(arg1:string):Promise<void>;

export function UnsubscribeLogs(arg1:string):Promise<void>;

export function UnsubscribeStats(arg1:string):Promise<void>;

export function UpsertSchedule(arg1:main.UpsertScheduleRequest):Promise<string>;
